servers:
- url: http://localhost:8888
paths:
  /ReEdgeGPT/chat:
    post:
      description: Chat with bing
      tags:
      - GPT
      requestBody:
        description: Data that chat needed
        content:
          application/json:
            schema:
              properties:
                prompt:
                  type: string
                  example: How to boil the eggs
                conversation_style:
                  type: string
                  enum:
                  - creative
                  - balanced
                  - precise
                  default: balanced
                simplify_response:
                  type: boolean
                attachment:
                  type: object
                  properties:
                    image_url:
                      type: string
                      default: null
                    filename:
                      type: string
                      default: null
                    base64_image:
                      type: string
                      default: null
      responses:
        '200':
          description: Success chat
          content:
            application/json:
              schema:
                properties:
                  text:
                    type: string
                  author:
                    type: string
                  sources:
                    type: string
                  sources_link:
                    type: string
                  suggestions:
                    type: array
                    example:
                    - How do I know if the eggs are fresh?
                    - What is a soft-boiled egg?
                    - Can you give me some recipes with boiled eggs?
                  messages_left:
                    type: integer
                    example: 29
                  max_messages:
                    type: integer
                    example: 30
  /ReEdgeGPT/image:
    post:
      description: Generate image using DALL3-E
      tags:
      - GPT
      requestBody:
        description: prompt
        content:
          application/json:
            schema:
              properties:
                prompt:
                  type: string
      responses:
        '200':
          description: Success generate image
          content:
            application/json:
              schema:
                properties:
                  images:
                    type: array
                    example:
                    - image_url1
                    - image_url2
                    - image_url3
info:
  title: ReEdgeGPT Example API Doc
  version: 1.0.0
openapi: 3.0.2
